name       : libTAS
version    : 1.4.0
release    : 9
source     :
    - https://github.com/clementgallet/libTAS/archive/v1.4.0.tar.gz : 88068fe4f60e7d9b42d11d92bf35090ad196bfcb6f433a517cf95276e4977c33
license    : GPL-3.0-or-later
component  : games
summary    : Toolset for creating tool-assisted speedruns
description: |
    libTAS is a Linux-only toolset for creating tool-assisted speedruns. It mostly supports SDL, but is being actively developed to support other engines as well. It's already been used for some GDQ runs, including the Mari0 speedrun at AGDQ2019.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(libswresample)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(sdl2)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - extra-cmake-modules
rundeps    :
    - ffmpeg
    - sdl2
    - gdb
setup      : |
    %patch -p1 < $pkgfiles/replace-icon-with-preferences-gaming.patch
    %reconfigure
build      : |
    %make
install    : |
    %make_install
