name       : libTAS
version    : 1.3.5
release    : 6
source     :
    - https://github.com/clementgallet/libTAS/archive/v1.3.5.tar.gz : ee468f54a638fbdebb0c362562dafcdeee4b6eb2c1279fd3c333f53a19f12803
license    : GPL-3.0-or-later
component  : games
summary    : Toolset for creating tool-assisted speedruns
description: |
    libTAS is a Linux-only toolset for creating tool-assisted speedruns. It mostly supports SDL, but is being actively developed to support other engines as well. It's already been used for some GDQ runs, including the Mari0 speedrun at AGDQ2019.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(libswresample)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(sdl2)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - extra-cmake-modules
rundeps    :
    - ffmpeg
    - sdl2
    - gdb
setup      : |
    %patch -p1 < $pkgfiles/replace-icon-with-preferences-gaming.patch
    %reconfigure
build      : |
    %make
install    : |
    %make_install
