name       : libTAS
version    : 1.3.4
release    : 2
source     :
    - https://github.com/clementgallet/libTAS/archive/v1.3.4.tar.gz : c82da9d31aff6fbfaa1453f3e4fae7b3627f672a6bce27ff7f662fbaa80b9bee
license    : GPL-3.0-or-later
component  : games
summary    : Toolset for creating tool-assisted speedruns
description: |
    libTAS is a Linux-only toolset for creating tool-assisted speedruns. It mostly supports SDL, but is being actively developed to support other engines as well. It's already been used for some GDQ runs, including the Mari0 speedrun at AGDQ2019.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(libswresample)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(sdl2)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-keysyms)
    - extra-cmake-modules
rundeps    :
    - ffmpeg
    - sdl2
    - gdb
setup      : |
    echo "Icon=preferences-desktop-gaming" >> libTAS.desktop
build      : |
    mkdir build && cd build
    cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
    %make
install    : |
    cd build
    %make_install
